//! End-to-end CLI tests: fixture creation, git repos, adapter matrices,
//! exit codes, and the pre-push hook guards.

use std::fs;
use std::path::Path;
use std::process::{Command, Output};

const BIN: &str = env!("CARGO_BIN_EXE_vdrift");

fn vdrift() -> Command {
    let mut c = Command::new(BIN);
    c.env_remove("CI")
        .env_remove("VDRIFT_SKIP")
        .env_remove("VDRIFT_RUNNING");
    c
}

fn run(c: &mut Command) -> Output {
    c.output().expect("failed to run vdrift")
}

fn stdout(o: &Output) -> String {
    String::from_utf8_lossy(&o.stdout).into_owned()
}

fn stderr(o: &Output) -> String {
    String::from_utf8_lossy(&o.stderr).into_owned()
}

fn git(dir: &Path, args: &[&str]) {
    let out = Command::new("git")
        .arg("-C")
        .arg(dir)
        .args(args)
        .output()
        .expect("failed to run git");
    assert!(
        out.status.success(),
        "git {args:?}: {}",
        String::from_utf8_lossy(&out.stderr)
    );
}

fn write(path: &Path, contents: &str) {
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    fs::write(path, contents).unwrap();
}

/// Creates a temp dir initialized as a git repo with a test identity.
fn fixture(name: &str) -> tempfile::TempDir {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    git(root, &["init", "-q", "-b", "main"]);
    git(root, &["config", "user.email", "test@example.com"]);
    git(root, &["config", "user.name", "Test User"]);
    let _ = name;
    dir
}

fn commit_all(dir: &Path, message: &str) {
    git(dir, &["add", "-A"]);
    git(dir, &["commit", "-q", "-m", message]);
}

fn init_npm_fixture(dir: &Path) {
    write(
        &dir.join("package.json"),
        r#"{
  "name": "app",
  "version": "2.0.0"
}
"#,
    );
    write(
        &dir.join("README.md"),
        "# app v2.0.0\n\nUse version 1.9.0 with npm:\n\n    npm install app@1.9.0\n",
    );
    commit_all(dir, "chore: initial");
}

// ---------------------------------------------------------------- detection

#[test]
fn npm_scan_detects_canonical_and_candidate() {
    let d = fixture("scan");
    init_npm_fixture(d.path());

    let out = run(vdrift().args(["scan", "--json"]).current_dir(d.path()));
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
    let v: serde_json::Value = serde_json::from_str(&stdout(&out)).unwrap();
    assert_eq!(v["project"]["type"], "node");
    assert_eq!(v["sources"][0]["file"], "package.json");
    assert_eq!(v["sources"][0]["version"], "2.0.0");
    assert_eq!(v["sources"][0]["kind"], "canonical");
    let readmes: Vec<_> = v["candidates"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|c| c["file"].as_str().unwrap().ends_with("README.md"))
        .collect();
    assert_eq!(readmes.len(), 1);
}

#[test]
fn check_reports_drift_with_exit_1() {
    let d = fixture("check");
    init_npm_fixture(d.path());
    write(
        &d.path().join(".vdrift.toml"),
        "[references]\nfiles = [\"README.md\"]\n",
    );

    let out = run(vdrift().args(["check", "--json"]).current_dir(d.path()));
    assert_eq!(out.status.code(), Some(1), "{}", stdout(&out));
    let v: serde_json::Value = serde_json::from_str(&stdout(&out)).unwrap();
    assert_eq!(v["status"], "drift");
    assert_eq!(v["outdated"][0]["file"], "README.md");
    assert_eq!(v["outdated"][0]["version"], "1.9.0");
    assert_eq!(v["canonical"]["version"], "2.0.0");
}

#[test]
fn sync_fixes_text_reference() {
    let d = fixture("sync");
    init_npm_fixture(d.path());
    write(
        &d.path().join(".vdrift.toml"),
        "[references]\nfiles = [\"README.md\"]\n",
    );

    let out = run(vdrift().args(["sync"]).current_dir(d.path()));
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
    let readme = fs::read_to_string(d.path().join("README.md")).unwrap();
    assert!(readme.contains("2.0.0"));
    assert!(!readme.contains("1.9.0"));

    let out = run(vdrift().args(["check", "--json"]).current_dir(d.path()));
    assert_eq!(out.status.code(), Some(0), "{}", stdout(&out));
}

// ------------------------------------------------------------------ cargo

#[test]
fn cargo_lock_is_a_derived_reference() {
    let d = fixture("cargo");
    write(
        &d.path().join("Cargo.toml"),
        "[package]\nname = \"lib\"\nversion = \"0.3.1\"\n",
    );
    write(
        &d.path().join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 3\n\n[[package]]\nname = \"lib\"\nversion = \"0.3.1\"\n",
    );
    commit_all(d.path(), "chore: initial");

    let out = run(vdrift().args(["scan", "--json"]).current_dir(d.path()));
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
    let v: serde_json::Value = serde_json::from_str(&stdout(&out)).unwrap();
    let kinds: Vec<&str> = v["sources"]
        .as_array()
        .unwrap()
        .iter()
        .map(|s| s["kind"].as_str().unwrap())
        .collect();
    assert!(kinds.contains(&"canonical"));
    assert!(kinds.contains(&"derived"));

    // Bump updates both manifest and lockfile.
    let out = run(vdrift()
        .args(["apply", "--version", "0.3.2", "--no-commit"])
        .current_dir(d.path()));
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
    let lock = fs::read_to_string(d.path().join("Cargo.lock")).unwrap();
    assert!(lock.contains("version = \"0.3.2\""));
    let manifest = fs::read_to_string(d.path().join("Cargo.toml")).unwrap();
    assert!(manifest.contains("version = \"0.3.2\""));
}

// ------------------------------------------------------------- generic yaml

#[test]
fn generic_json_can_be_a_reference() {
    let d = fixture("jsonref");
    write(
        &d.path().join("helm/Chart.yaml"),
        "apiVersion: v2\nname: app\nversion: 3.1.0\n",
    );
    write(
        &d.path().join(".vdrift.toml"),
        "[version]\nsource = \"helm/Chart.yaml\"\n[references]\nfiles = [\"docs/version.json\"]\n",
    );
    write(
        &d.path().join("docs/version.json"),
        "{\n  \"version\": \"3.0.9\"\n}\n",
    );
    commit_all(d.path(), "chore: initial");

    let out = run(vdrift().args(["check", "--json"]).current_dir(d.path()));
    assert_eq!(out.status.code(), Some(1), "{}", stdout(&out));
    let v: serde_json::Value = serde_json::from_str(&stdout(&out)).unwrap();
    assert_eq!(v["canonical"]["file"], "helm/Chart.yaml");
    assert_eq!(v["canonical"]["version"], "3.1.0");

    let out = run(vdrift().args(["sync"]).current_dir(d.path()));
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
    let json = fs::read_to_string(d.path().join("docs/version.json")).unwrap();
    let v: serde_json::Value = serde_json::from_str(&json).unwrap();
    assert_eq!(v["version"], "3.1.0");
}

// ------------------------------------------------------------------- plan

#[test]
fn plan_proposes_patch_after_fix_commit() {
    let d = fixture("plan");
    init_npm_fixture(d.path());

    let out = run(vdrift().args(["plan", "--json"]).current_dir(d.path()));
    let v: serde_json::Value = serde_json::from_str(&stdout(&out)).unwrap();
    assert_eq!(v["status"], "synchronized");

    write(&d.path().join("src.js"), "export const a = 1;\n");
    commit_all(d.path(), "fix: correct the widget calculation");

    let out = run(vdrift().args(["plan", "--json"]).current_dir(d.path()));
    let v: serde_json::Value = serde_json::from_str(&stdout(&out)).unwrap();
    assert_eq!(v["status"], "needs_update");
    assert_eq!(v["suggested_version"], "2.0.1");
    assert_eq!(v["reason"]["type"], "fix");
}

#[test]
fn plan_proposes_major_after_breaking_commit() {
    let d = fixture("plan_major");
    init_npm_fixture(d.path());
    write(&d.path().join("src.js"), "export const a = 1;\n");
    commit_all(d.path(), "feat!: drop legacy support");

    let out = run(vdrift().args(["plan", "--json"]).current_dir(d.path()));
    let v: serde_json::Value = serde_json::from_str(&stdout(&out)).unwrap();
    assert_eq!(v["suggested_version"], "3.0.0");
    assert_eq!(v["reason"]["type"], "major");
}

// -------------------------------------------------------------------- git

#[test]
fn apply_commit_creates_bump_commit() {
    let d = fixture("apply_commit");
    init_npm_fixture(d.path());

    let out = run(vdrift()
        .args(["apply", "--version", "2.1.0", "--commit"])
        .current_dir(d.path()));
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));

    let log = Command::new("git")
        .arg("-C")
        .arg(d.path())
        .args(["log", "-1", "--format=%s"])
        .output()
        .unwrap();
    assert_eq!(
        String::from_utf8_lossy(&log.stdout).trim(),
        "chore: bump version to 2.1.0"
    );
    let pkg: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(d.path().join("package.json")).unwrap()).unwrap();
    assert_eq!(pkg["version"], "2.1.0");
}

#[test]
fn apply_refuses_dirty_target_file() {
    let d = fixture("dirty");
    init_npm_fixture(d.path());
    write(
        &d.path().join(".vdrift.toml"),
        "[references]\nfiles = [\"README.md\"]\n",
    );
    // Uncommitted change to README that still carries a version.
    write(
        &d.path().join("README.md"),
        "# app\n\nUse 1.9.0 with npm.\n",
    );

    let out = run(vdrift().args(["sync"]).current_dir(d.path()));
    assert_eq!(out.status.code(), Some(6), "{}", stderr(&out));
    // Nothing was partially applied: package.json still has the old version.
    let pkg: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(d.path().join("package.json")).unwrap()).unwrap();
    assert_eq!(pkg["version"], "2.0.0");

    // --force overrides the guard.
    let out = run(vdrift().args(["sync", "--force"]).current_dir(d.path()));
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
}

// --------------------------------------------------------------- exit codes

#[test]
fn invalid_version_argument_is_exit_7() {
    let d = fixture("badver");
    init_npm_fixture(d.path());
    let out = run(vdrift()
        .args(["apply", "--version", "not.a.version", "--json"])
        .current_dir(d.path()));
    assert_eq!(out.status.code(), Some(7));
    let v: serde_json::Value = serde_json::from_str(&stdout(&out)).unwrap();
    assert_eq!(v["error"]["code"], "INVALID_VERSION");
}

#[test]
fn no_project_is_unsupported_exit_3() {
    let d = fixture("noproject");
    write(&d.path().join("notes.txt"), "hello\n");
    commit_all(d.path(), "chore: initial");
    let out = run(vdrift()
        .args(["apply", "--version", "1.0.0"])
        .current_dir(d.path()));
    assert_eq!(out.status.code(), Some(3));
}

// ------------------------------------------------------------------- hook

/// Writes the pre-push stdin line to the child. The hook may exit before
/// consuming stdin (early guards), so a broken pipe is acceptable.
fn feed_hook_stdin(child: &mut std::process::Child, line: &str) {
    use std::io::Write;
    if let Some(mut stdin) = child.stdin.take() {
        let _ = stdin.write_all(line.as_bytes());
    }
}

fn hook_stdin_line(dir: &Path, remote_oid: &str) -> String {
    let oid = Command::new("git")
        .arg("-C")
        .arg(dir)
        .args(["rev-parse", "HEAD"])
        .output()
        .unwrap();
    let oid = String::from_utf8_lossy(&oid.stdout).trim().to_string();
    format!("refs/heads/main {oid} refs/heads/main {remote_oid}")
}

#[test]
fn hook_skips_when_push_is_clean() {
    let d = fixture("hook_clean");
    init_npm_fixture(d.path());

    let mut c = vdrift();
    c.args(["hook", "pre-push"]).current_dir(d.path());
    c.stdin(std::process::Stdio::piped());
    let mut child = c.spawn().unwrap();
    feed_hook_stdin(
        &mut child,
        &hook_stdin_line(d.path(), "0000000000000000000000000000000000000000"),
    );
    let out = child.wait_with_output().unwrap();
    assert_eq!(out.status.code(), Some(0), "{}", stdout(&out));
}

#[test]
fn hook_skips_when_environment_is_ci() {
    let d = fixture("hook_ci");
    init_npm_fixture(d.path());
    write(&d.path().join("feature.js"), "export const x = 1;\n");
    commit_all(d.path(), "feat: add x");

    let mut c = vdrift();
    c.args(["hook", "pre-push"])
        .current_dir(d.path())
        .env("CI", "true");
    c.stdin(std::process::Stdio::piped());
    let mut child = c.spawn().unwrap();
    feed_hook_stdin(
        &mut child,
        &hook_stdin_line(d.path(), "0000000000000000000000000000000000000000"),
    );
    let out = child.wait_with_output().unwrap();
    assert_eq!(out.status.code(), Some(0), "{}", stdout(&out));
}

#[test]
fn hook_skips_when_explicitly_disabled() {
    let d = fixture("hook_disabled");
    init_npm_fixture(d.path());
    write(
        &d.path().join(".vdrift.toml"),
        "[behavior]\nenabled = false\n",
    );

    let mut c = vdrift();
    c.args(["hook", "pre-push"]).current_dir(d.path());
    c.stdin(std::process::Stdio::piped());
    let mut child = c.spawn().unwrap();
    feed_hook_stdin(
        &mut child,
        &hook_stdin_line(d.path(), "0000000000000000000000000000000000000000"),
    );
    let out = child.wait_with_output().unwrap();
    assert_eq!(out.status.code(), Some(0), "{}", stdout(&out));
}

// --------------------------------------------------------- global integration

#[test]
fn init_status_uninstall_roundtrip() {
    let base = tempfile::tempdir().unwrap();
    let config_home = base.path().join("xdg");
    fs::create_dir_all(&config_home).unwrap();

    let mut c = vdrift();
    c.args(["init"]).env("XDG_CONFIG_HOME", &config_home);
    let out = run(&mut c);
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));

    let hooks_path = Command::new("git")
        .args(["config", "--global", "core.hooksPath"])
        .env("XDG_CONFIG_HOME", &config_home)
        .output()
        .unwrap();
    let hp = String::from_utf8_lossy(&hooks_path.stdout)
        .trim()
        .to_string();
    assert!(hp.contains("vdrift/hooks"), "unexpected hooksPath: {hp}");

    let dispatcher = config_home.join("vdrift/hooks/pre-push");
    assert!(dispatcher.is_file(), "dispatcher hook not written");

    let out = run(vdrift()
        .args(["status"])
        .env("XDG_CONFIG_HOME", &config_home));
    assert_eq!(out.status.code(), Some(0));

    // Uninstall is deterministic with --yes.
    let out = run(vdrift()
        .args(["uninstall", "--yes"])
        .env("XDG_CONFIG_HOME", &config_home));
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
    assert!(!dispatcher.exists(), "dispatcher hook should be removed");
}

// ------------------------------------------------------------- agents (JSON)

#[test]
fn agent_workflow_is_deterministic() {
    let d = fixture("agent");
    init_npm_fixture(d.path());
    write(
        &d.path().join(".vdrift.toml"),
        "[references]\nfiles = [\"README.md\"]\n",
    );

    // 1. check --json
    let out = run(vdrift().args(["check", "--json"]).current_dir(d.path()));
    assert_eq!(out.status.code(), Some(1));
    let v: serde_json::Value = serde_json::from_str(&stdout(&out)).unwrap();
    assert_eq!(v["status"], "drift");
    let target = v["canonical"]["version"].as_str().unwrap().to_string();

    // 2. plan --json (read-only)
    let out = run(vdrift().args(["plan", "--json"]).current_dir(d.path()));
    assert_eq!(out.status.code(), Some(0));
    let _v: serde_json::Value = serde_json::from_str(&stdout(&out)).unwrap();

    // 3. apply --version --commit (deterministic, no prompts)
    let out = run(vdrift()
        .args(["apply", "--version", &target, "--commit", "--force"])
        .current_dir(d.path()));
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));

    // 4. verify --ci
    let out = run(vdrift().args(["verify", "--ci"]).current_dir(d.path()));
    assert_eq!(out.status.code(), Some(0), "{}", stdout(&out));
}
